In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("amazing restaurant", 30)#it gives the number betwee
#n 1 to 30

[7, 23]

In [5]:
one_hot("amazing restaurant done by vishesh", 50)#it gives the number betwee
#n 1 to 50

[42, 18, 9, 13, 12]

In [6]:
vocab_size = 30
encoded_reviews=[one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[14, 5], [7, 23], [10, 1], [23, 3, 24], [22, 24, 2], [20, 5], [8, 24, 11], [21, 17], [21, 26], [16, 26]]


In [8]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews, 
                             maxlen=max_length, padding='post')
print(padded_reviews)#padding is addded to make sure that uniform length is there

[[14  5  0]
 [ 7 23  0]
 [10  1  0]
 [23  3 24]
 [22 24  2]
 [20  5  0]
 [ 8 24 11]
 [21 17  0]
 [21 26  0]
 [16 26  0]]


In [10]:
emedded_vector_size=5
model=Sequential()
model.add(Embedding(vocab_size,emedded_vector_size,
                     input_length=max_length,name='embedding'))
#embedding layer is added and it is used to convert 
# the words into vectors and the input length is the length of the words
model.add(Flatten())#Flatten the array
model.add(Dense(1,activation='sigmoid'))



In [11]:
X=padded_reviews
y=sentiment
model.compile(optimizer='adam',
              loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.fit(X,y,epochs=50,verbose=0)
#verbose is used to show the output of the model


In [13]:
loss, accuracy = model.evaluate(X, y, verbose=0)

In [14]:
accuracy

1.0

In [17]:
weights=model.get_layer('embedding').get_weights()[0]
#it gives the weights of the embedding layer
len(model.get_layer('embedding').get_weights()[0])

30

In [18]:
weights[0]

array([ 0.06548715, -0.03509999,  0.03091211, -0.00565438, -0.02708413],
      dtype=float32)

In [19]:
weights[15]

array([-0.03602735,  0.03338958,  0.0262471 ,  0.03528371,  0.00058508],
      dtype=float32)