In [1]:
import numpy as np

In [2]:

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [3]:
def mae(y_true,y_predicted):
    tota_error=0
    for yt,yp in zip(y_true,y_predicted):
        tota_error+=abs(yt-yp)
    print("Mean absolute error",tota_error)

In [4]:
mae(y_true,y_predicted)

2.5


In [8]:
#same function using numpy
np.mean(np.abs(y_predicted-y_true))

0.5

In [9]:
np.log([0])

C:\Users\vishe\AppData\Local\Temp\ipykernel_14472\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
eplison=1e-15


In [16]:
y_predicted

array([1, 1, 0, 0, 1])

In [17]:
y_predicted_new=[max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [18]:
y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [19]:
y_predicted_new=np.array(y_predicted_new)

In [20]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [21]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [22]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,eplison) for i in y_predicted]
    y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [23]:

log_loss(y_true, y_predicted)

17.2696280766844