In [1]:
import tensorflow as tf

In [2]:
daily_sales_number=[21,22,-100,31,-1,32,34,31]


In [3]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)


21
22
-100
31
-1
32
34
31


In [6]:
#to filter the function
tf_dataset=tf_dataset.filter(lambda x:x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [7]:
#to change the or them map the values 
tf_dataset=tf_dataset.map(lambda x:x*72)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [8]:
tf_dataset=tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)
#shuffle the data is the best way to shuffle the data
#it works on the buffer size of the data with the process of the data
#it will shuffle the data in the buffer size of the data
#explain with examplw
#buffer size is 2
#data is 1,2,3,4,5,6,7,8
#buffer size is 2
#it will take the first two data and shuffle them
#it will take the next two data and shuffle them
#it will take the next two data and shuffle them
#it will take the next two data and shuffle them


1512
1584
2304
2232
2448
2232


In [9]:
for sales_batch in tf_dataset.batch(2).as_numpy_iterator():
    print(sales_batch)

[1584 2232]
[2304 2448]
[2232 1512]


In [12]:
#in one line code

tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset=tf_dataset.filter(lambda x:x>0).map(lambda y:y*72).shuffle(2).batch(2)

for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1512 2232]
[1584 2448]
[2232 2304]


In [13]:
images_ds=tf.data.Dataset.list_files('images/*/*',shuffle=False)

for file in images_ds.take(5):
    print(file.numpy())

b'images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg'
b'images\\cat\\7 Foods Your Cat Can_t Eat.jpg'
b'images\\cat\\A cat appears to have caught the....jpg'
b'images\\cat\\Adopt-A-Cat Month\xc2\xae - American Humane....jpg'
b'images\\cat\\All About Your Cat_s Tongue.jpg'


In [14]:
images_ds=images_ds.shuffle(200)
for file in images_ds.take(5):
    print(file.numpy())

b'images\\dog\\Why Grumpy Dogs Outperform Friendly....jpg'
b'images\\cat\\Cats really do need their humans_ even....jpg'
b'images\\dog\\Largest Dog Breeds \xe2\x80\x93 American Kennel Club.jpg'
b'images\\dog\\Are Dogs Really Color-Blind_ _ Britannica.jpg'
b'images\\dog\\Trained dogs can smell coronavirus in....jpg'


In [15]:
class_names=["cat","dog"]


In [18]:
image_count=len(images_ds)
image_count

130

In [19]:
train_size=int(0.8*image_count)
train_ds=images_ds.take(train_size)
test_ds=images_ds.skip(train_size)

In [20]:
len(train_ds),len(test_ds)

(104, 26)

In [22]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path,os.path.sep)[-2]

In [23]:
for label in train_ds.map(get_label):
    print(label)

tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=

In [24]:
def process_image(file_path):
    label=get_label(file_path)
    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,[128,128])
    return img,label

In [27]:
for img,label in train_ds.map(process_image).take(3):
    print(img,label)

tf.Tensor(
[[[124.27344   85.35376   75.74048 ]
  [149.46606   88.408936  70.342285]
  [148.05078   87.05078   68.05078 ]
  ...
  [130.        75.        54.      ]
  [132.        77.        56.      ]
  [133.8125    78.8125    57.8125  ]]

 [[122.98169  107.32666  107.90088 ]
  [129.68701  101.046875  99.08594 ]
  [130.1128   103.33154  101.09326 ]
  ...
  [132.        77.        56.      ]
  [132.84766   77.84766   56.847656]
  [131.1875    76.1875    55.1875  ]]

 [[143.625    150.6477   150.8728  ]
  [143.58545  151.29468  151.14282 ]
  [145.33154  149.6836   150.52393 ]
  ...
  [129.        74.        53.      ]
  [132.85718   76.85718   53.857178]
  [130.375     74.375     51.375   ]]

 ...

 [[ 98.62402   99.62402   94.62402 ]
  [100.09277  101.09277   96.09277 ]
  [ 89.15283   90.15283   85.15283 ]
  ...
  [100.06738  100.06738   98.06738 ]
  [ 99.77051   99.77051   97.77051 ]
  [ 89.463135  89.463135  87.463135]]

 [[101.72046  102.72046   97.72046 ]
  [109.14258  110.14258  1

In [28]:
def scale(image,label):
    return image/255.0,label


In [ ]:
train_ds=train_ds.map(process_image).map(scale)
